const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const {MongoClient}=require('mongodb');
const PORT=process.env.PORT||3000,PUB=path.join(__dirname,'public'),sessions=new Map();
const MONGODB_URI=process.env.MONGODB_URI||process.env.MONGO_URI||'';
const MONGODB_DB=process.env.MONGODB_DB||'matka_club';
if(!MONGODB_URI) throw new Error('MONGODB_URI is required');
const client=new MongoClient(MONGODB_URI);
let collection, state;
function seed(){const bundled=path.join(__dirname,'db.json');try{return normalize(JSON.parse(fs.readFileSync(bundled,'utf8')))}catch{return normalize({users:{},results:[],transactions:[],requests:[],loginHistory:[],settings:{},predictions:[]})}}
function normalize(d){d=d&&typeof d==='object'?d:{};d.users=d.users&&typeof d.users==='object'?d.users:{};d.results=Array.isArray(d.results)?d.results:[];d.transactions=Array.isArray(d.transactions)?d.transactions:[];d.requests=Array.isArray(d.requests)?d.requests:[];d.loginHistory=Array.isArray(d.loginHistory)?d.loginHistory:[];d.settings=d.settings&&typeof d.settings==='object'?d.settings:{};d.predictions=Array.isArray(d.predictions)?d.predictions:[];return d}
async function initMongo(){await client.connect();const db=client.db(MONGODB_DB);collection=db.collection('app_state');let doc=await collection.findOne({_id:'main'});if(!doc){state=seed();await collection.insertOne({_id:'main',data:state,updatedAt:new Date()});}else state=normalize(doc.data);console.log(`MongoDB connected: ${MONGODB_DB}.app_state`)}
function read(){return state}
function write(d){state=normalize(d);return collection.replaceOne({_id:'main'},{$set:{data:state,updatedAt:new Date()}},{upsert:true}).catch(e=>console.error('MongoDB write error:',e.message))}
function json(res,c,d){res.writeHead(c,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(d))}
function body(req){return new Promise((ok,no)=>{let s='';req.on('data',c=>{s+=c;if(s.length>1e6)req.destroy()});req.on('end',()=>{try{ok(s?JSON.parse(s):{})}catch(e){no(e)}})})}
function safe(u){return {username:u.username,role:u.role,coins:Number(u.coins||0),blocked:!!u.blocked,createdBy:u.createdBy||null,createdAt:u.createdAt||null}}
function auth(req,role){const h=req.headers.authorization||'',t=h.startsWith('Bearer ')?h.slice(7):'',u=sessions.get(t);if(!u||!u.username)return null;if(role&&u.role!==role)return null;return u}
function amount(v){return Number.isInteger(Number(v))&&Number(v)>0?Number(v):0}
function validPatti(p){p=String(p||'').trim();return /^\d{3}$/.test(p)&&Number(p[0])<=Number(p[1])&&Number(p[1])<=Number(p[2])}
function logTx(d,entry){d.transactions.unshift({id:crypto.randomUUID(),time:Date.now(),...entry})}
async function api(req,res){const d=read(),u=new URL(req.url,'http://x');
 if(req.method==='POST'&&u.pathname==='/api/login'){const b=await body(req),x=d.users[String(b.username||'')];if(!x||x.password!==String(b.password||''))return json(res,401,{error:'Invalid username or password'});if(x.blocked)return json(res,403,{error:'Account is blocked'});const t=crypto.randomBytes(32).toString('hex');sessions.set(t,{username:x.username,role:x.role});d.loginHistory.unshift({time:Date.now(),username:x.username,role:x.role});d.loginHistory=d.loginHistory.slice(0,500);write(d);return json(res,200,{token:t,user:safe(x)})}
 if(req.method==='POST'&&u.pathname==='/api/logout'){const a=auth(req);if(a)sessions.delete((req.headers.authorization||'').slice(7));return json(res,200,{ok:true})}
 if(req.method==='GET'&&u.pathname==='/api/me'){const a=auth(req),x=a&&d.users[a.username];if(!x||x.blocked)return json(res,401,{error:'Unauthorized'});return json(res,200,{user:safe(x)})}
 if(req.method==='GET'&&u.pathname==='/api/state'){const a=auth(req),x=a&&d.users[a.username];if(!x||x.blocked)return json(res,401,{error:'Unauthorized'});let users=[];if(x.role==='SUPERADMIN')users=Object.values(d.users).map(safe);else if(x.role==='ADMIN')users=[x,...Object.values(d.users).filter(v=>v.createdBy===x.username&&v.role==='USER')].map(safe);else users=[x].map(safe);const tx=x.role==='SUPERADMIN'?d.transactions:d.transactions.filter(t=>t.actor===x.username||t.target===x.username||t.admin===x.username);const reqs=x.role==='ADMIN'?d.requests.filter(r=>r.admin===x.username):x.role==='SUPERADMIN'?d.requests:d.requests.filter(r=>r.user===x.username||r.admin===x.username);return json(res,200,{results:d.results,users,transactions:tx,requests:reqs,loginHistory:x.role==='SUPERADMIN'?d.loginHistory:d.loginHistory.filter(l=>l.username===x.username||d.users[l.username]?.createdBy===x.username),settings:d.settings,predictions:x.role==='USER'?d.predictions.filter(p=>p.user===x.username):d.predictions})}
 if(req.method==='POST'&&u.pathname==='/api/result/open'){const a=auth(req,'SUPERADMIN');if(!a)return json(res,403,{error:'Only SUPERADMIN can publish results'});const b=await body(req),r=d.results.find(z=>z.market===b.market),p=String(b.patti||'');if(!r)return json(res,404,{error:'Market not found'});if(!validPatti(p))return json(res,400,{error:'Patti must be 3 digits in non-decreasing order, e.g. 111, 112, 122, 149, 479'});r.openPatti=p;r.openAnk=String(p.split('').reduce((s,n)=>s+Number(n),0)%10);r.jodi=r.openAnk+(r.closeAnk==='-'?'-':r.closeAnk);r.published=true;r.updatedAt=Date.now();logTx(d,{type:'RESULT_OPEN',actor:a.username,market:r.market,patti:p});write(d);settlePredictionsForMarket(r.market);return json(res,200,{result:r})}
 if(req.method==='POST'&&u.pathname==='/api/result/close'){const a=auth(req,'SUPERADMIN');if(!a)return json(res,403,{error:'Only SUPERADMIN can update close result'});const b=await body(req),r=d.results.find(z=>z.market===b.market),p=String(b.patti||'');if(!r)return json(res,404,{error:'Market not found'});if(!r.published)return json(res,400,{error:'Open result must be published first'});if(!validPatti(p))return json(res,400,{error:'Patti must be 3 digits in non-decreasing order, e.g. 111, 112, 122, 149, 479'});r.closePatti=p;r.closeAnk=String(p.split('').reduce((s,n)=>s+Number(n),0)%10);r.jodi=r.openAnk+r.closeAnk;r.updatedAt=Date.now();logTx(d,{type:'RESULT_CLOSE',actor:a.username,market:r.market,patti:p});write(d);settlePredictionsForMarket(r.market);return json(res,200,{result:r})}
 if(req.method==='POST'&&u.pathname==='/api/admin/create'){const a=auth(req,'SUPERADMIN');if(!a)return json(res,403,{error:'Only SUPERADMIN can create admins'});const b=await body(req),name=String(b.name||'').trim(),username=String(b.username||'').trim(),password=String(b.password||'');if(!name||!/^[A-Za-z0-9_.]{3,30}$/.test(username)||password.length<4)return json(res,400,{error:'Name, valid username and password are required'});if(d.users[username])return json(res,400,{error:'Username already exists'});d.users[username]={username,name,password,role:'ADMIN',coins:0,blocked:false,createdBy:a.username,createdAt:Date.now()};logTx(d,{type:'ADMIN_CREATED',actor:a.username,target:username});write(d);return json(res,200,{user:safe(d.users[username])})}
 if(req.method==='POST'&&u.pathname==='/api/admin/toggle'){const a=auth(req,'SUPERADMIN');if(!a)return json(res,403,{error:'Only SUPERADMIN'});const b=await body(req),x=d.users[b.username];if(!x||x.role!=='ADMIN')return json(res,404,{error:'Admin not found'});x.blocked=!x.blocked;logTx(d,{type:x.blocked?'ADMIN_BLOCKED':'ADMIN_UNBLOCKED',actor:a.username,target:x.username});write(d);return json(res,200,{user:safe(x)})}
 if(req.method==='POST'&&u.pathname==='/api/admin/reset-password'){const a=auth(req,'SUPERADMIN');if(!a)return json(res,403,{error:'Only SUPERADMIN'});const b=await body(req),x=d.users[b.username];if(!x||x.role!=='ADMIN'||String(b.password||'').length<4)return json(res,400,{error:'Valid admin and password required'});x.password=String(b.password);logTx(d,{type:'ADMIN_PASSWORD_RESET',actor:a.username,target:x.username});write(d);return json(res,200,{ok:true})}
 if(req.method==='POST'&&u.pathname==='/api/coins'){const a=auth(req,'SUPERADMIN');if(!a)return json(res,403,{error:'Only SUPERADMIN can manage admin coins'});const b=await body(req),x=d.users[b.admin],sa=d.users[a.username],n=amount(b.amount);if(!x||x.role!=='ADMIN'||!n)return json(res,400,{error:'Valid admin and amount required'});if(b.action==='deposit'){if(sa.coins<n)return json(res,400,{error:'Insufficient superadmin coins'});sa.coins-=n;x.coins+=n}else if(b.action==='withdraw'){if(x.coins<n)return json(res,400,{error:'Admin has insufficient coins'});x.coins-=n;sa.coins+=n}else return json(res,400,{error:'Invalid action'});logTx(d,{type:b.action==='deposit'?'ADMIN_COIN_DEPOSIT':'ADMIN_COIN_WITHDRAW',actor:a.username,target:x.username,admin:x.username,amount:n,balance:x.coins});write(d);return json(res,200,{admin:safe(x),superadmin:safe(sa)})}
 if(req.method==='POST'&&u.pathname==='/api/user/create'){const a=auth(req,'ADMIN');if(!a)return json(res,403,{error:'Only ADMIN'});const b=await body(req),username=String(b.username||'').trim(),password=String(b.password||'');if(!/^[A-Za-z0-9_.]{3,30}$/.test(username)||password.length<4)return json(res,400,{error:'Valid username and password required'});if(d.users[username])return json(res,400,{error:'Username already exists'});d.users[username]={username,password,role:'USER',coins:0,blocked:false,createdBy:a.username,createdAt:Date.now()};logTx(d,{type:'USER_CREATED',actor:a.username,target:username,admin:a.username});write(d);return json(res,200,{user:safe(d.users[username])})}
 if(req.method==='POST'&&u.pathname==='/api/user/toggle'){const a=auth(req,'ADMIN');if(!a)return json(res,403,{error:'Only ADMIN'});const b=await body(req),x=d.users[b.username];if(!x||x.role!=='USER'||x.createdBy!==a.username)return json(res,404,{error:'User not found'});x.blocked=!x.blocked;logTx(d,{type:x.blocked?'USER_BLOCKED':'USER_UNBLOCKED',actor:a.username,target:x.username,admin:a.username});write(d);return json(res,200,{user:safe(x)})}
 if(req.method==='POST'&&u.pathname==='/api/user/reset-password'){const a=auth(req,'ADMIN');if(!a)return json(res,403,{error:'Only ADMIN'});const b=await body(req),x=d.users[b.username];if(!x||x.role!=='USER'||x.createdBy!==a.username||String(b.password||'').length<4)return json(res,400,{error:'Valid user and password required'});x.password=String(b.password);logTx(d,{type:'USER_PASSWORD_RESET',actor:a.username,target:x.username,admin:a.username});write(d);return json(res,200,{ok:true})}
 if(req.method==='POST'&&u.pathname==='/api/user/coins'){const a=auth(req,'ADMIN');if(!a)return json(res,403,{error:'Only ADMIN'});const b=await body(req),x=d.users[b.username],ad=d.users[a.username],n=amount(b.amount);if(!x||x.role!=='USER'||x.createdBy!==a.username||!n)return json(res,400,{error:'Valid user and amount required'});if(b.action==='add'){if(ad.coins<n)return json(res,400,{error:'Insufficient admin coins'});ad.coins-=n;x.coins+=n}else if(b.action==='subtract'){if(x.coins<n)return json(res,400,{error:'User has insufficient coins'});x.coins-=n;ad.coins+=n}else return json(res,400,{error:'Invalid action'});logTx(d,{type:b.action==='add'?'USER_COIN_ADD':'USER_COIN_SUBTRACT',actor:a.username,target:x.username,admin:a.username,amount:n,balance:x.coins});write(d);return json(res,200,{user:safe(x),admin:safe(ad)})}
 if(req.method==='POST'&&u.pathname==='/api/user/request'){const a=auth(req,'USER');if(!a)return json(res,403,{error:'Only USER'});const x=d.users[a.username],ad=d.users[x.createdBy];const b=await body(req),n=amount(b.amount);if(!ad||!n||!['add','subtract'].includes(b.type))return json(res,400,{error:'Invalid request'});if(b.type==='subtract'&&x.coins<n)return json(res,400,{error:'Insufficient coins'});const id=crypto.randomUUID();if(b.type==='subtract')x.coins-=n;d.requests.unshift({id,time:Date.now(),type:b.type,amount:n,user:x.username,admin:ad.username,status:'pending'});logTx(d,{type:'COIN_REQUEST',actor:x.username,target:ad.username,admin:ad.username,amount:n,requestId:id,requestType:b.type});write(d);return json(res,200,{ok:true})}
 if(req.method==='POST'&&u.pathname==='/api/request/review'){const a=auth(req,'ADMIN');if(!a)return json(res,403,{error:'Only ADMIN'});const b=await body(req),r=d.requests.find(q=>q.id===b.id&&q.admin===a.username&&q.status==='pending');if(!r)return json(res,404,{error:'Request not found'});const x=d.users[r.user],ad=d.users[a.username];if(!x)return json(res,404,{error:'User not found'});if(b.action==='approve'){if(r.type==='add'){if(ad.coins<r.amount)return json(res,400,{error:'Insufficient admin coins'});ad.coins-=r.amount;x.coins+=r.amount}else{ad.coins+=r.amount}}else if(b.action==='reject'){if(r.type==='subtract')x.coins+=r.amount}else return json(res,400,{error:'Invalid action'});r.status=b.action==='approve'?'approved':'rejected';r.reviewedAt=Date.now();logTx(d,{type:'REQUEST_'+r.status.toUpperCase(),actor:a.username,target:x.username,admin:a.username,amount:r.amount,requestId:r.id});write(d);return json(res,200,{ok:true})}
 /* V28 safe prediction tracker: points only, never deducted from coin balance */
 function predictionMatches(p,r){
   if(p.market!==r.market)return false;
   if(p.type==='OPEN_CLOSE') return p.side==='OPEN'?String(r.openAnk)===String(p.number):String(r.closeAnk)===String(p.number);
   if(p.type==='PATTI') return p.side==='OPEN'?String(r.openPatti)===String(p.number):String(r.closePatti)===String(p.number);
   if(p.type==='JODI') return String(r.jodi)===String(p.number);
   return false;
 }
 function settlePredictionsForMarket(market){
   const r=d.results.find(x=>x.market===market); if(!r)return;
   let changed=false;
   for(const p of d.predictions){
     if(p.market!==market||p.status!=='PENDING')continue;
     const ready=p.type==='OPEN_CLOSE'?(p.side==='OPEN'?r.published:r.closeAnk!=='-'):(p.type==='PATTI'?r.closeAnk!=='-':r.closeAnk!=='-');
     if(!ready)continue;
     p.status=predictionMatches(p,r)?'CORRECT':'INCORRECT';p.settledAt=Date.now();changed=true;
   }
   if(changed)write(d);
 }
 if(req.method==='GET'&&u.pathname==='/api/game-settings'){return json(res,200,{ok:true,settings:{},note:'Prediction points only; coin balance is not used'})}
 if(req.method==='POST'&&u.pathname==='/api/game-settings'){return json(res,403,{error:'Prediction return settings are not available'})}
 if(req.method==='POST'&&u.pathname==='/api/predictions'){
   const a=auth(req,'USER');if(!a)return json(res,403,{error:'Only USER'});
   const b=await body(req),items=Array.isArray(b.items)?b.items:[];
   if(!items.length||items.length>100)return json(res,400,{error:'Add at least one prediction'});
   const valid=[];
   for(const raw of items){
     const market=String(raw.market||'').trim(),type=String(raw.type||''),side=String(raw.side||'').toUpperCase(),number=String(raw.number||'').trim(),points=Number(raw.points??raw.coins);
     if(!d.results.some(r=>r.market===market))return json(res,400,{error:'Invalid market'});
     if(!['OPEN_CLOSE','PATTI','JODI'].includes(type))return json(res,400,{error:'Invalid prediction type'});
     if(type==='OPEN_CLOSE'&&(!['OPEN','CLOSE'].includes(side)||!/^[0-9]$/.test(number)))return json(res,400,{error:'Open/Close requires one digit and Open or Close side'});
     if(type==='PATTI'&&(!['OPEN','CLOSE'].includes(side)||!validPatti(number)))return json(res,400,{error:'Patti must be 3 digits in ascending/non-decreasing order'});
     if(type==='JODI'&&!/^\d{2}$/.test(number))return json(res,400,{error:'Jodi must be exactly 2 digits (00-99)'});
     if(!Number.isInteger(points)||points<10)return json(res,400,{error:'Minimum 10 prediction points per selection'});
     valid.push({market,type,side:type==='JODI'?'':side,number,predictionPoints:points});
   }
   const created=[];for(const p of valid){const item={id:crypto.randomUUID(),user:a.username,time:Date.now(),status:'PENDING',...p};d.predictions.unshift(item);created.push(item);logTx(d,{type:'PREDICTION_RECORDED',actor:a.username,target:p.market,amount:p.predictionPoints,predictionId:item.id,category:p.type});}
   await write(d);for(const p of created)settlePredictionsForMarket(p.market);
   return json(res,200,{ok:true,predictions:created,user:safe(d.users[a.username])});
 }
 if(req.method==='POST'&&u.pathname==='/api/settings'){const a=auth(req,'SUPERADMIN');if(!a)return json(res,403,{error:'Only SUPERADMIN'});const b=await body(req);if(typeof b.siteName==='string')d.settings.siteName=b.siteName.trim()||'MATKA CLUB';if(typeof b.support==='string')d.settings.support=b.support.trim();write(d);return json(res,200,{settings:d.settings})}
 return json(res,404,{error:'Not found'})}
const server=http.createServer((req,res)=>{if(req.url.startsWith('/api/'))return api(req,res).catch(e=>json(res,500,{error:e.message||'Server error'}));let p=new URL(req.url,'http://x').pathname;if(p==='/')p='/index.html';const f=path.resolve(PUB,'.'+p);if(!f.startsWith(path.resolve(PUB)+path.sep)||!fs.existsSync(f)||!fs.statSync(f).isFile())return res.writeHead(404).end('Not found');res.writeHead(200,{'Content-Type':path.extname(f)==='.html'?'text/html; charset=utf-8':'application/javascript; charset=utf-8','Cache-Control':'no-store'});res.end(fs.readFileSync(f))});
initMongo().then(()=>server.listen(PORT,()=>console.log(`MATKA CLUB V28 running on http://localhost:${PORT}`))).catch(e=>{console.error('MongoDB startup failed:',e.message);process.exit(1)});
